### ISSUE TITLE
Provisional Company

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#135]
As a developer
I need to be able to create a provisional company

**Comment by joaopapereira** [comment]
Expected:
- [ ] Create field in the database to mark the company as provisional
- [ ] Create a function in the model to change the company status

Rspec tests

**Comment by joaopapereira** [comment]
The field for this should be created at the Companies table

**Comment by patmbolger** [comment]
Suggest calling this field 'status', since "provisional' is just one of a number of types of status we will eventually need.  For instance:

Status = 'Under Review'  (this is what we've been referring to as "provisional'
Status = 'Rejected" (decision was made not to associated with this company)
Status = 'Not Active' (company has ceased to be associated with the agency - perhaps the agency rescinded the association, or the company went out of business, etc.)

**Comment by amba178** [comment]
@patrick: 
It is good to have few types of status, but practically this makes it a bit complex.
For example
 Rejected than what is next? deleted from the database?
Not Active than what is next?
etc
I would leave it as original chore state.
What do you think?

**Comment by patmbolger** [comment]
I am not asking for adding more status types at this point.  I am just suggesting that you make the status field that we need to add now more generic - that is:

1) Add a 'status' field rather than 'provisional' field.
2) Consider defining status value (the string defining the status) in a constant defined in the Company model, in a hash that has a symbol as key and the string as the value (see AgencyRole::ROLE as an example).

Some rationale for this:

1) We have not yet defined the life cycle requirements for a Company (aka Employer).  However, we have stumbled on to the need to tracking the registration process state via a status indicator. When we consider the full life cycle, along with historical reporting and other considerations, I am pretty sure that we will need to track more life cycle states.

2) Since the status is not just a field in the DB - it is piece of information that will drive workflow and hence our app logic.  It is cleaner (and maybe faster) to use a status key (symbol) in our conditional logic than a string.  Also, we can change the string later (to meet client requirements) without changing much of our app software that is conditional on status.  That is, we can change:

    STATUS = { UR: 'Provisional' }

to

    STATUS = { UR: 'Under Review' }

without impacting code as much (if at all).

So, to be clear, I am not asking you to define any state beyond 'Under Review' (a term I prefer to 'Provisional').  So, we don't have to define all life cycle states now in order to implement this initial need for a single status to be tracked.

(this is a long post, but this is a topic worth discussion and hence worth talking about - we can discuss on tonight's call.  Also, all comments above apply to any place where we need status tracking - CompanyPerson, etc.)

**Comment by amba178** [comment]
well, obviously these are small text and  I agree using constant in the model for efficiency ....

**Comment by sidhene** [comment]
I could add the new field and set it to 'provisional' during the application process as part of story #21. Shall I?

**Comment by patmbolger** [comment]
The story is not needed anymore as 'status' was added as part of work on #21 and #134.
