### ISSUE TITLE
Provisional Employer

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#136]
As a developer
I need to be able to create a provisional employer

**Comment by joaopapereira** [comment]
Expected:
- [ ] Create field in the database to mark the employer as provisional
- [ ] Create a function in the model to change the provisional status

Rspec tests

**Comment by joaopapereira** [comment]
This field should be created at company_people level

**Comment by patmbolger** [comment]
Suggest calling this field 'status', since "provisional' is just one of a number of types of status we will eventually need.  For instance:

Status = 'Under Review'  (this is what we've been referring to as "provisional'
Status = 'Rejected" (decision was made not to associated with this company/company person)
Status = 'Not Active' (company person has left company, etc.)

There will almost certainly be other status values we need to track.

**Comment by patmbolger** [comment]
The story is not needed anymore as 'status' was added as part of work on #21 and #134.
