### ISSUE TITLE
DRY out forms to edit multiple user

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#169]
As a developer 
I need to change the Forms to use reuse views that are shared between forms

**Comment by joaopapereira** [comment]
The needed forms to be reviewed are:
Agency Person
Job Seeker

**Comment by patmbolger** [comment]
and CompanyPerson

**Comment by sidhene** [comment]
and companies/_form
This is a duplicate of company_registrations/_form 

There is also duplication in the cucumber tests for this section - instead of referring to the same view, it is spelled out individually in several tests. This means that when we add or move  a field, that change must be made separately for each repeat.

**Comment by vijayakarumudi** [comment]
I am working on dry out form for edit users.

**Comment by vijayakarumudi** [comment]
I completed dry out forms  for AgencyPerson,CompanyPerson and JobSeeker. I will create the PR today.
