### ISSUE TITLE
Add Pundit auth to company people controller

### ISSUE THREAD

**Issue by patmbolger** [AgileVentures/MetPlus_tracker#434]
As a developer
I need to enforce authorization for user action

**Comment by patmbolger** [comment]
* See authorizations by role here: https://docs.google.com/spreadsheets/d/1XmlNwVebV3ix1wU0GgXk39mOanHviDLZdod_xdnfqpE/edit#gid=0

* Review Pundit: https://github.com/elabs/pundit

* Review existing implementation of Pundit (e.g. application_policy, etc.)

This story includes:

- [ ] Add company_people_policy.rb

- [ ] In company_people_controller.rb, authorize actions consistent with auth matrix

- [ ] Add rspec tests (policies/company_people_spec.rb)

- [ ] Add acceptance tests (cucumber - might want to consolidate these into one feature file)

**Comment by arun1595** [comment]
I am almost done with this task but I am having an issue with authorization for `list_profile` action. This is what I have as of now.
```ruby
def list_people?
  (agency_admin? user and agency_related_to_company?(user.agency, record.company)) or
      user.is_company_person? record.company
end
```
The problem is we don't have a `company_person` instance available in the `list_profile` action to perform the authorization.

From pundit documentation,

  > If you don't have an instance for the first argument to authorize, then you can pass the class.

But it still does not solve the problem as we need to get the company using `record.company` in `list_profile?` method.

I also tried doing this in the `list_profile` action.

```ruby
  # in list_profile
  @company_person = pets_user
  authorize @company_person
```
This introduces another issue cause `pets_user` can be a `company_person` or `agency_person` and if `@company_person` is an instance of `AgencyPerson`, we can't call `record.company` as it raises a `NoMethodError` since an `AgencyPerson` doesn't have a `#company` method.


Suggested Fix:
  I was wondering why we would need the `list_people` action in the `CompanyPeopleController` when we are only using the `company` instance in the action. 
(`get 'company_people/:company_id/list_people/:people_type`)

I think it makes sense to move this action to `CompanyController` since this involves with finding the company instance and does not operate on a `company_person` instance or its collection.

Thoughts?

**Comment by patmbolger** [comment]
I agree that we should refactor the action `list_people` from the company person controller to the company controller.  The resource is `company`, as you note.
