### ISSUE TITLE
Download a resume as an employer

### ISSUE THREAD

**Issue by lollypop27** [AgileVentures/MetPlus_tracker#445]
As JD, CM, AA, CC and a CA
When I receive a JS application
I would like the ability to download their resume to my local machine

**Comment by lollypop27** [comment]
http://stackoverflow.com/questions/27957766/how-to-render-word-documentdoc-docx-in-browser-using-javascript

http://api.rubyonrails.org/classes/ActionController/DataStreaming.html#method-i-send_file

**Comment by patmbolger** [comment]
For this feature, the user (anyone who has authorization to view the job application _show_ page) will be able to download the applicant's résumé to their PC.

This story includes:

- [ ] Add 'Download' button to job app show page, next to résumé field (on same row in table)
  * There is no need to confirm the DL action, as the user will be presented with a dialog where she can specify where to download the résumé to - the user can simply cancel out of that dialog to stop the action.
  * The button will activate a link to the controller with appropriate route and application ID

- [ ] Add route for download action to routes.rb

- [ ] Add `download_applicant_resume` action to `job_applications_controller.rb`.
  * Invoke `ResumeCruncher.download_resume(resume_id)` to download the résumé (from the cruncher) to a Tempfile on the Rails server (will be placed in the /tmp directory).  (this file needs to be deleted (via `unlink`) when user action is completed)
  * Use `send_data` to send the file to the browser.  The default value of `disposition` attribute (_attachment_) should be used, as this should cause the browser to prompt for a download location.  (use `send_data` instead of `send_file`, since we need to confirm delivery of the file before deleting the file.  The former should not return until the file has been downloaded on the user's machine).
  * Call `.unlink` on the file to delete it.  Close the file *before* unlinking (see discussion of "unlink-before-close" here: https://ruby-doc.org/stdlib-1.9.3/libdoc/tempfile/rdoc/Tempfile.html#method-i-unlink)
  * Note that the controller action should _not_ `render` a view, but simply send the data to the browser and return.
  * See `CompanyMailer.application_received` for an example of downloading a résumé.

- [ ] Add functional test(s) for this action to `job_applications_controller_spec.rb`.
  * It would be preferable to test two user responses to the download prompt - accept the download or cancel the download.  If this cannot be done these can be deferred to the acceptance (cucumber) tests.

- [ ] Add scenarios to `job_application.feature`.  Navigate to an existing job application and test download 1) accept and delivery on PC, or, 2) cancel the download.
