### ISSUE TITLE
Salary range

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#627]
As  a company person
I want to add a salary range
So that my Job as more complete information

Given I am creating a Job
When I start filling up the information
Then the hourly salary should be selected

** Success Cases **

Given I am creating a Job
And I correctly fill the form
When I the salary starting and top range are empty
And I press create
Then the  job is created successfully

Given I am creating a Job
And I correctly fill the form
When I the salary starting salary range as the value 3000
And the period is selected to monthly
And top range are empty
And I press create
Then the job is created successfully

Given I am creating a Job
And already have values in the salary
When I change the the period of the salary
Then the previously entered salaries should not be change

** Error Cases **

Given I am creating a Job
When I type 'asd' in the salary start range
Then I should se an error 'Invalid start salary range'

Given I am creating a Job
When I type 'asd' in the salary top range
Then I should se an error 'Invalid top salary range'

Given I am creating a Job
And I correctly fill the form
When the salary starting salary range is empty
And the top salary range is not empty
Then I should se an error 'Invalid starting salary range'

Given I am creating a Job
And I correctly fill the form
When the salary starting salary range higher then the top salary range
Then I should se an error 'Top salary range should be higher then the starting range'

**Comment by joaopapereira** [comment]
Mockup: https://www.figma.com/file/0M8E7avMDk5Iu24LgmFgOq7C/MetPlus

**Comment by patmbolger** [comment]
Rather than "Starting" and "Top" field labels I suggest "Minimum" and "Maximum".  ("starting" label implies something different than what is intended - what _is_ intended is "the starting salary will range between the min and max value, depending on experience").

This story requires:

- [ ] Add `min_salary`, `max_salary` and `salary_period` attributes to Job model
  - Model validations to be consistent with above scenarios
- [ ] Add test(s) to model unit spec tests
- [ ] Add these attributes to Job form
- [ ] Add these attributes to Job show view
- [ ] Add acceptance (cucumber) tests, consistent with above scenarios
