### ISSUE TITLE
Employer search for JS

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/MetPlus_tracker#99]
As an Employer
When I search for Job Seeker
I will see all the Job Seeker in the system

**Comment by patmbolger** [comment]
Added label 'ResumeCruncher' to this story since  simple list of job seekers - shown to an employer - is not very useful without information categorizing the skills of the job seeker.

When the résumé cruncher is ready, we can add a robust job seeker search capability that allows an employer to search by JS category, skill(s), location, experience level, etc.

**Comment by patmbolger** [comment]
See related story #383.

**Comment by joaopapereira** [comment]
The resume cruncher part of this is complete, need to understand  the need for this feature

**Comment by patmbolger** [comment]
We have résumé-to-job matching now and that is sufficient.
